[tool.poetry]
name = "opengostop"
version = "0.1.0"
description = ""
authors = ["Youngmin Kim <ymkim92@gmail.com>"]
license = "MIT"

packages = [
    { include = "src" },
]

[tool.poetry.scripts]
pytimer = "simpletimer.timer:pytimer"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
